[workspace]
members = ["attester"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
sp1-sdk = "2.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
